language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    - DISTRIB="ubuntu-no-matplotlib" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
      MATPLOTLIB_VERSION="1.1.1" SCIKIT_LEARN_VERSION="0.11"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="*" SCIPY_VERSION="*"
      MATPLOTLIB_VERSION="*" SCIKIT_LEARN_VERSION="*" COVERAGE="true"

install: 
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    # Copy setup.cfg to TEST_RUN_FOLDER where we are going to run the tests from
    # Mainly for nose config settings
    - cp setup.cfg "$TEST_RUN_FOLDER"
    # We want to back out of the current working directory to make
    # sure we are using nilearn installed in site-packages rather
    # than the one from the current working directory
    # Parentheses (run in a subshell) are used to leave
    # the current directory unchanged
    - (cd "$TEST_RUN_FOLDER" && make -f $OLDPWD/Makefile test-code)

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - if [[ "$COVERAGE" == "true" ]]; then cp "$TEST_RUN_FOLDER/.coverage" .; coveralls || echo "failed"; fi
