language: python

virtualenv:
  system_site_packages: true

env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    - DISTRIB="ubuntu-no-matplotlib" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.9.0" SCIPY_VERSION="0.15.1"
      MATPLOTLIB_VERSION="1.4" SKLEARN_VERSION="0.15.2"

install: 
    - source continuous_integration/install.sh
    - python continuous_integration/show-python-packages-versions.py

script:
    - make clean
    - make test-code
