language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from

matrix:
  include:
    # FLAKE8 linting on diff wrt common ancestor with upstream/master
    # Note: the python value is only there to trigger allow_failures
    - python: 2.7
      env: DISTRIB="conda" PYTHON_VERSION="2.7" FLAKE8_VERSION="*" SKIP_TESTS="true"

install: source continuous_integration/install.sh

before_script: make clean

script: source continuous_integration/test_script.sh

after_success: source continuous_integration/after_success.sh  
